name: CI
run-name: "CI run by @${{ github.actor }}, event: ${{ github.event_name }}"
on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
    workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    run-functional-tests:
        permissions:
            contents: read
        uses: ./.github/workflows/functional-tests.yml
    run-security-tests:
        uses: ./.github/workflows/security-tests.yml
    upload-gem:
        permissions:
            packages: write
            contents: read
        needs: [run-functional-tests, run-security-tests]
        uses: ./.github/workflows/upload-gem.yml