name: CI
run-name: "CI run by @${{ github.actor }}, event: ${{ github.event_name }}"
on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
    workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    run-tests:
        permissions:
            contents: read
        uses: ./.github/workflows/tests.yml
        secrets: inherit
    upload-gem:
        permissions:
            packages: write
            contents: read
        needs: [run-tests]
        if: ${{ always() }}
        uses: ./.github/workflows/upload-gem.yml
        secrets: inherit