name: SecurityTests
on:
    workflow_call:
    workflow_dispatch:

jobs:
    security-tests:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            actions: read
            statuses: read
            security-events: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.0
                  bundler-cache: true
            - name: SAST(Talisman) - Detect secrets in commits
              uses: carhartl/talisman-secrets-scan-action@v1.4.0
            - name: Dependency Check
              uses: dependency-check/Dependency-Check_Action@main
              with:
                  project: 'hello_world_hex_ruby'
                  path: '.'
                  format: 'HTML'
                  out: 'dependency-check'
            - name: Upload Dependency Check Report
              uses: actions/upload-artifact@v4
              with:
                  name: dependency-check
                  path: ${{github.workspace}}/dependency-check
            - name: Set up Snyk
              uses: snyk/actions/setup@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            - name: Check Snyk Version
              run: snyk --version
            - name: Run Snyk test with logging 0
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
                SNYK_ORGANIZATION_ID: ${{ secrets.SNYK_ORGANIZATION_ID }}
              uses: snyk/actions/ruby@master
              continue-on-error: true # To make sure that SARIF upload gets called even if the test fails
              with:
                args: --all-projects --sarif-file-output=snyk.sarif --org=$SNYK_ORGANIZATION_ID --debug
            - name: Run Snyk test with logging
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              run: |
                if [ -z "%SNYK_TOKEN%" ]; then
                  echo "SNYK_TOKEN is not set"
                  exit 1
                else
                  echo "SNYK_TOKEN is set: ${SNYK_TOKEN}"
                fi
                export SNYK_TOKEN=$SNYK_TOKEN && snyk test --all-projects --sarif-file-output=snyk.sarif --debug
            - name: Run Snyk test
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              run: snyk test --all-projects --sarif-file-output=snyk.sarif
            - name: Upload Snyk Report
              uses: github/codeql-action/upload-sarif@v2
              with:
                  sarif_file: snyk.sarif
