name: SecurityTests
on:
    workflow_call:
    workflow_dispatch:

jobs:
    security-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.0
                  bundler-cache: true
            - name: Set up Snyk
              uses: snyk/actions/setup@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            - name: Check Snyk Version
              run: snyk --version
            - name: snyk auth with debug
              if: always()
              run: |
                    snyk auth --auth-type=token --debug
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
                  SNYK_ORGANIZATION_ID: ${{ secrets.SNYK_ORGANIZATION_ID }}
            - name: use snyk github action with debug
              if: always()
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
                SNYK_ORGANIZATION_ID: ${{ secrets.SNYK_ORGANIZATION_ID }}
              uses: snyk/actions/ruby@master
              continue-on-error: true # To make sure that SARIF upload gets called even if the test fails
              with:
                args: --sarif-file-output=snyk.sarif -d
            - name: Upload Snyk Report
              uses: github/codeql-action/upload-sarif@v2
              with:
                  sarif_file: snyk.sarif
