name: Upload gem

on:
    workflow_call:
    workflow_dispatch:

jobs:
    upload-gem:
        continue-on-error: true
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 2.7
                  bundler-cache: true
            - name: Build and Publish gem
              uses: dawidd6/action-publish-gem@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}